homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_secret
  longitude: !secret longitude_secret
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

# Sensors
sensor:
  - platform: darksky
    api_key: !secret dark_sky_api_key_secret
    name: "Outside"
    scan_interval:
      days: 0
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
    monitored_conditions:
      - temperature
      - humidity
  # Weather prediction
  - platform: yr
  - platform: trafikverket_train
    api_key: !secret trafikverket_api_key_secret
    trains:
    - name: "Train to work 0709"
      from: "Falkenberg"
      to: "Göteborg C"
      time: "07:09"
      weekday: [mon, tue, wed, thu, fri]
    - name: "Train from work 1625"
      from: "Göteborg C"
      to: "Falkenberg"
      time: "16:25"
      weekday: [mon, tue, wed, thu, fri]

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key_secret
    mode: daily

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
  
ios:

cloud:
    
beerbolaget:
  api_key: !secret systembolaget_secret
  image_url: "https://www.systembolaget.se/api/productsearch/search/sok-dryck"
  store: "Sandgatan"

lovelace:
    mode: yaml

google_assistant:
  project_id: !secret google_assistant_project_id_secret
  api_key: !secret google_assistant_api_key_secret
  exposed_domains:
    - input_boolean
    - scene
    - script
    - switch
    - fan
    - light
    - lock
    - cover
    - media_player
    - climate
    - vacuum
    - sensor

homekit:
  auto_start: false

http:
  base_url: !secret base_url_secret
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url_secret

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include lights.yaml
scene: !include scenes.yaml
