title: Home

resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/beerbolaget-card/beerbolaget-card.js
    type: js

views:
  - badges:
      - sensor.yr_symbol
      - sun.sun
      - device_tracker.stinas_iphone
      - device_tracker.viktors_iphone_2
      - sensor.fermentation_temperature
    cards:
      - columns: 3
        entities:
          - entity: switch.lounge_plug
          - entity: switch.living_room_plug
          - entity: switch.kitchen_plug
          - entity: light.kitchen_table_bulb
          - entity: light.kitchen_countertop_bulb
          - entity: light.lounge_bulb
          - entity: light.living_room_bulb
          - entity: light.bedroom_bed_bulb
          - entity: light.bedroom_drawer_bulb
        show_icon: true
        show_name: true
        show_state: true
        title: Switches
        type: glance
      - entities:
          - entity: person.viktor
          - entity: person.stina
        show_header_toggle: false
        title: Persons
        type: entities
      - entity: weather.dark_sky
        type: weather-forecast
      - type: custom:mini-media-player
        entity: media_player.living_room
        hide:
          power: true
          icon: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Sonos Living Room
            - entity_id: media_player.kitchen
              name: Sonos Kitchen
      - entities:
          - sensor.drying_room_temperature
          - sensor.bedroom_temperature
          - sensor.outside_temperature
          - sensor.kitchen_temperature
        hours_to_show: 24
        title: Temperature
        type: history-graph
      - entities:
          - sensor.drying_room_humidity
          - sensor.bedroom_humidity
          - sensor.outside_humidity
          - sensor.kitchen_humidity
        hours_to_show: 24
        title: Humidity
        type: history-graph
      - type: custom:beerbolaget-card
        entity: sensor.beerbolaget
        rating: true
        user_ratings: true
        filter_local: true
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - sensor.fermentation_temperature
        hours_to_show: 24
        title: Fermentation Temperature
        type: history-graph
      - entities:
          - sensor.kitchen_fridge_temperature_2
          - sensor.basement_fridge_temperature
        hours_to_show: 24
        title: Fridge Temperature
        type: history-graph
      - entities:
          - sensor.kitchen_freezer_temperature_2
          - sensor.basement_freezer_temperature
        hours_to_show: 24
        title: Freezer Temperature
        type: history-graph
    title: Monitoring
