title: Home

resources:
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/beerbolaget-card/beerbolaget-card.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module

views:
  - badges:
      - sensor.yr_symbol
      - sun.sun
      - device_tracker.stinas_iphone
      - device_tracker.viktors_iphone_2
      - sensor.fermentation_temperature
    cards:
      - columns: 1
        entities:
          - type: custom:fold-entity-row
            head:
              type: custom:slider-entity-row
              entity: light.ground_floor_lights
              hide_state: true
            open: true
            entities:
              - type: custom:slider-entity-row
                entity: light.kitchen_table_bulb
                hide_state: true
              - type: custom:slider-entity-row
                entity: light.kitchen_countertop_bulb
                hide_state: true
              - type: custom:slider-entity-row
                entity: light.lounge_bulb
                hide_state: true
              - type: custom:slider-entity-row
                entity: light.living_room_bulb
                hide_state: true
          - type: custom:fold-entity-row
            head:
              type: custom:slider-entity-row
              entity: light.bedroom_lights
              hide_state: true
            open: true
            entities:
              - type: custom:slider-entity-row
                entity: light.bedroom_bed_bulb
                hide_state: true
              - type: custom:slider-entity-row
                entity: light.bedroom_drawer_bulb
                hide_state: true
          - type: custom:fold-entity-row
            head:
              group.all_switches
            open: true
            entities:
              - switch.lounge_plug
              - switch.living_room_plug
              - switch.kitchen_plug
        show_icon: false
        show_name: true
        show_state: false
        title: Lights & Switches
        type: entities
      - entities:
          - entity: person.viktor
          - entity: person.stina
        show_header_toggle: false
        title: Persons
        type: entities
      - entity: weather.dark_sky
        type: weather-forecast
      - type: custom:mini-media-player
        entity: media_player.living_room
        hide:
          power: true
          icon: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Sonos Living Room
            - entity_id: media_player.kitchen
              name: Sonos Kitchen
      - entities:
          - sensor.drying_room_temperature
          - sensor.bedroom_temperature
          - sensor.outside_temperature
          - sensor.kitchen_temperature
        hours_to_show: 24
        title: Temperature
        type: history-graph
      - entities:
          - sensor.drying_room_humidity
          - sensor.bedroom_humidity
          - sensor.outside_humidity
          - sensor.kitchen_humidity
        hours_to_show: 24
        title: Humidity
        type: history-graph
      - type: custom:beerbolaget-card
        entity: sensor.beerbolaget
        rating: true
        user_ratings: true
        filter_local: true
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - sensor.fermentation_temperature
        hours_to_show: 24
        title: Fermentation Temperature
        type: history-graph
      - entities:
          - sensor.kitchen_fridge_temperature_2
          - sensor.basement_fridge_temperature
        hours_to_show: 24
        title: Fridge Temperature
        type: history-graph
      - entities:
          - sensor.kitchen_freezer_temperature_2
          - sensor.basement_freezer_temperature
        hours_to_show: 24
        title: Freezer Temperature
        type: history-graph
    title: Monitoring
